### ISSUE TITLE
question: status and purpose...

### ISSUE THREAD

**Issue by clojj** [karlotness/tree-sitter.el#1]
Hi, very interesting to see tree-sitter integrated to emacs
Is this just providing the tree-sitter (runtime-)API or also actual syntax-highlighting/and/or language-modes to emacs ?

**Comment by karlotness** [comment]
Right now it's just the API and also re-parsing buffers on an idle timer. The basic API should be working so anyone who wants to play with the library or build something with it (syntax highlighting or use it for code folding) should be able to do that, even if installing it isn't trivial.

There's no syntax highlighting or anything else yet and I may not have very much time to really work on something like that. It would probably be possible to put together some sort of CSS-selector system like Atom uses and then integrate that with jit-lock to do fontification.

I'm not sure if that's something that would make sense to include here, or whether this should stay pretty bare-bones and just provide the API for other packages to build on, again somewhat closer to Atom's separate language packages.
